spring:
   datasource:
     url: jdbc:postgresql://localhost:5432/staybook_db
     username:  dev_user
     password:  dev_password
     driver-class-name: org.postgresql.Driver
  
   jpa:
    hibernate:
      ddl-auto: update
    show-sql: true